# Generated by Django 4.2.13 on 2024-05-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_restaurante_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_restaurante',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.restaurante'),
        ),
    ]
