# Generated by Django 4.2.13 on 2024-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_restaurante_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='tipo_cocina',
            field=models.CharField(default='Español', max_length=100),
        ),
    ]
